# University of Texas, Dallas - Hackathon Oct 2017


## Problem 3: Somerville Happiness Survey
                


In [ ]:
#initial_code, the code written here will be shown to user, write here initial setup to help user get started.

## Importing Libraries

In [41]:
import numpy as np
import pandas as pd
import csv
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import metrics
%matplotlib inline

##  Loading Data

In [2]:
#city.columns
city = pd.read_csv('https://data.somervillema.gov/api/views/yevj-2b33/rows.csv')
city.describe()

Combined_ID         Year  \
count  6545.000000  6545.000000   
mean   3273.000000  2011.172040   
std    1889.523088     0.735317   
min       1.000000  2011.000000   
25%    1637.000000  2011.000000   
50%    3273.000000  2011.000000   
75%    4909.000000  2011.000000   
max    6545.000000  2015.000000   

       How.satisfied.are.you.with.your.neighborhood.  \
count                                     378.000000   
mean                                        7.828042   
std                                         1.970823   
min                                         1.000000   
25%                                         7.000000   
50%                                         8.000000   
75%                                         9.000000   
max                                        10.000000   

       How.proud.are.you.to.be.a.Somerville.resident._2015  \
count                                         182.000000     
mean                                            8.192308     
std                                             1.811976     
min                                             1.000000     
25%                                             7.000000     
50%                                             9.000000     
75%                                            10.000000     
max                                            10.000000     

       How.would.you.rate.the.following..The.availability.of.information.about.city.services._2015  \
count                                         182.000000                                             
mean                                            4.241758                                             
std                                             0.838845                                             
min                                             1.000000                                             
25%                                             4.000000                                             
50%                                             4.000000                                             
75%                                             5.000000                                             
max                                             5.000000                                             

       How.would.you.rate.the.following..The.cost.of.housing.  \
count                                         375.000000        
mean                                            2.742667        
std                                             1.185268        
min                                             1.000000        
25%                                             2.000000        
50%                                             3.000000        
75%                                             4.000000        
max                                             5.000000        

       How.would.you.rate.the.following..The.overall.quality.of.public.schools.  \
count                                         281.000000                          
mean                                            3.375445                          
std                                             1.086673                          
min                                             1.000000                          
25%                                             3.000000                          
50%                                             3.000000                          
75%                                             4.000000                          
max                                             5.000000                          

       How.would.you.rate.the.following..The.beauty.or.physical.setting.of.Somerville_2013  \
count                                         193.000000                                     
mean                                            3.466321                                     
std                                             0.879545                                    

In [3]:
city.groupby(by='Year',axis=0).count()

Combined_ID  How.happy.do.you.feel.right.now.  \
Year                                                  
2011         6167                              6167   
2013          193                               193   
2015          185                               184   

      How.satisfied.are.you.with.your.life.in.general.  \
Year                                                     
2011                                              6167   
2013                                               193   
2015                                               183   

      How.satisfied.are.you.with.Somerville.as.a.place.to.live.  \
Year                                                              
2011                                               6167           
2013                                                193           
2015                                                185           

      In.general..how.similar.are.you.to.other.people.you.know._2011  \
Year                                                                   
2011                                               6167                
2013                                                  0                
2015                                                  0                

      When.making.decisions..are.you.more.likely.to.seek.advice.or.decide.for.yourself._2011.  \
Year                                                                                            
2011                                               6167                                         
2013                                                  0                                         
2015                                                  0                                         

      How.satisfied.are.you.with.your.neighborhood.  \
Year                                                  
2011                                              0   
2013                                            193   
2015                                            185   

      How.proud.are.you.to.be.a.Somerville.resident._2015  \
Year                                                        
2011                                                  0     
2013                                                  0     
2015                                                182     

      How.would.you.rate.the.following..The.availability.of.information.about.city.services._2015  \
Year                                                                                                
2011                                                  0                                             
2013                                                  0                                             
2015                                                182                                             

      The.availability.of.affordable.housing_2011    ...     \
Year                                                 ...      
2011                                         6167    ...      
2013                                            0    ...      
2015                                            0    ...      

      What.is.your.race.or.ethnicity._2015  \
Year                                         
2011                                     0   
2013                                     0   
2015                                   182   

      Do.you.have.children.age.18.or.younger.who.live.with.you.  \
Year                                                              
2011                                                  0           
2013                                                187           
2015                                                183           

      Describe.your.housing.status.in.Somerville.  \
Year                                                
2011                                            0   
2013                                            0   
2015                                          181   

      Do.you.plan.t

### Divided the dataset by year

In [5]:
city_2011 = city[city.Year == 2011]
city_2013 = city[city.Year == 2013]
city_2015 = city[city.Year == 2015]

#### Creating a list of the columns with all values as NA for year 2011

In [6]:
na_col_list = city_2011.columns[city_2011.isnull().all()].tolist()

In [7]:
city_2011_nonull = city_2011.drop(na_col_list,axis=1)

In [8]:
city_2011_nonull.shape
city_2011_nonull.head(5)

Combined_ID  Year How.happy.do.you.feel.right.now.  \
378          379  2011                               10   
379          380  2011                                8   
380          381  2011                                7   
381          382  2011                                9   
382          383  2011                                4   

    How.satisfied.are.you.with.your.life.in.general.  \
378                                               10   
379                                                9   
380                                                7   
381                                                7   
382                                                4   

    How.satisfied.are.you.with.Somerville.as.a.place.to.live.  \
378                                                 10          
379                                                  9          
380                                                  8          
381                                                 10          
382                                                  6          

    In.general..how.similar.are.you.to.other.people.you.know._2011  \
378                                                 10               
379                                                  7               
380                                                  7               
381                                                  6               
382                                                  8               

    When.making.decisions..are.you.more.likely.to.seek.advice.or.decide.for.yourself._2011.  \
378                                                 10                                        
379                                                  2                                        
380                                                  7                                        
381                                                  9                                        
382                                                  6                                        

    The.availability.of.affordable.housing_2011  \
378                                           4   
379                                           5   
380                                           2   
381                                           r   
382                                           2   

    How.would.you.rate.the.following..The.overall.quality.of.public.schools.in.your.community._2011  \
378                                                  5                                                
379                                                  r                                                
380                                                  3                                                
381                                                  r                                                
382                                                  3                                                

    How.would.you.rate.the.following..The.beauty.or.physical.setting_2011  \
378                                                  4                      
379                                                  5                      
380                                                  3                      
381                                                  2                      
382                                                  4                      

    How.would.you.rate.the.following..The.effectiveness.of.the.local.police_2011_2013  \
378                                                  5                                  
379                                                  5                                  
380                                                  4                                  
381                                                  5                                  
382                                                  3                                  

    Wh

In [9]:
contents2011 = city_2011_nonull.columns
contents2011

Index(['Combined_ID', 'Year', 'How.happy.do.you.feel.right.now.',
       'How.satisfied.are.you.with.your.life.in.general.',
       'How.satisfied.are.you.with.Somerville.as.a.place.to.live.',
       'In.general..how.similar.are.you.to.other.people.you.know._2011',
       'When.making.decisions..are.you.more.likely.to.seek.advice.or.decide.for.yourself._2011.',
       'The.availability.of.affordable.housing_2011',
       'How.would.you.rate.the.following..The.overall.quality.of.public.schools.in.your.community._2011',
       'How.would.you.rate.the.following..The.beauty.or.physical.setting_2011',
       'How.would.you.rate.the.following..The.effectiveness.of.the.local.police_2011_2013',
       'What.is.your.gender._2011', 'Age.', 'Marital.status._2011',
       'What.is.your.race_2011_2013', 'How.long.have.you.lived.here.',
       'What.is.your.annual.household.income.'],
      dtype='object')

#### Dropping the columns with null values for Year 2013 and 2015

In [10]:
### This is for the 2013 year
na_col_list = city_2013.columns[city_2013.isnull().all()].tolist()
city_2013_nonull = city_2013.drop(na_col_list,axis=1)

### This is for the 2015 year
na_col_list = city_2015.columns[city_2015.isnull().all()].tolist()
city_2015_nonull = city_2015.drop(na_col_list,axis=1)

In [11]:
contents2015 = city_2015_nonull.columns
contents2015

Index(['Combined_ID', 'Year', 'How.happy.do.you.feel.right.now.',
       'How.satisfied.are.you.with.your.life.in.general.',
       'How.satisfied.are.you.with.Somerville.as.a.place.to.live.',
       'How.satisfied.are.you.with.your.neighborhood.',
       'How.proud.are.you.to.be.a.Somerville.resident._2015',
       'How.would.you.rate.the.following..The.availability.of.information.about.city.services._2015',
       'How.would.you.rate.the.following..The.cost.of.housing.',
       'How.would.you.rate.the.following..The.overall.quality.of.public.schools.',
       'How.would.you.rate.the.following..Your.trust.in.the.local.police_2015',
       'How.would.you.rate.the.following..The.maintenance.of.streets.and.sidewalks_2015',
       'How.would.you.rate.the.following..The.availability.of.social.community.events',
       'How.safe.do.you.feel.walking.in.your.community.at.night._2015',
       'How.satisfied.are.you.with.the.beauty.or.physical.setting.of.your.neighborhood.',
       'How.satisfi

### Keeping the columns which are common in all years

In [12]:
rem2011 = ['The.availability.of.affordable.housing_2011',
           'How.would.you.rate.the.following..The.beauty.or.physical.setting_2011',
           'When.making.decisions..are.you.more.likely.to.seek.advice.or.decide.for.yourself._2011.',
           'In.general..how.similar.are.you.to.other.people.you.know._2011',
            'Marital.status._2011']

city_2011_raw = city_2011_nonull.drop(rem2011, axis=1)

city_2011_raw.shape

(6167, 12)

In [14]:
rem2013 = ['How.would.you.rate.the.following..The.cost.of.housing.',
           'How.would.you.rate.the.following..The.beauty.or.physical.setting.of.Somerville_2013',
           'How.satisfied.are.you.with.your.neighborhood.',
           'How.would.you.rate.the.following..The.availability.of.social.community.events',
           'How.safe.do.you.feel.walking.in.your.neighborhood.at.night_2013',
           'How.would.you.rate.the.following..The.maintenance.of.streets..sidewalks..and..squares_2013',
           'How.satisfied.are.you.with.the.beauty.or.physical.setting.of.your.neighborhood.',
           'How.satisfied.are.you.with.the.appearance.of.parks.in.your.neighborhood._2013',
           'Are.you.of.Hispanic..Latino..or.Spanish.origin._2013',
           'Do.you.have.children.age.18.or.younger.who.live.with.you.',
           'Do.you.plan.to.move.away.from.Somerville.in.the.next.two.years.',
           'What.neighborhood.do.you.live.in.', 'Are.you.a.student.', 'Ward',
           'Precinct']

city_2013_raw = city_2013_nonull.drop(rem2013,axis = 1)

In [15]:
### Delelting the columns from 2015 which are not there in 2011

rem2015 = ['How.proud.are.you.to.be.a.Somerville.resident._2015',
          'How.would.you.rate.the.following..The.availability.of.information.about.city.services._2015',
          'How.would.you.rate.the.following..The.cost.of.housing.',
          'How.would.you.rate.the.following..The.maintenance.of.streets.and.sidewalks_2015',
          'How.would.you.rate.the.following..The.availability.of.social.community.events',
          'How.safe.do.you.feel.walking.in.your.community.at.night._2015',
          'How.satisfied.are.you.with.the.beauty.or.physical.setting.of.your.neighborhood.',
          'How.satisfied.are.you.with.the.appearance.of.parks.and.squares.in.your.neighborhood.',
          'What.language..other.than.English..do.you.speak.at.home._2015',
          'Do.you.have.children.age.18.or.younger.who.live.with.you.',
          'Describe.your.housing.status.in.Somerville.',
          'Do.you.plan.to.move.away.from.Somerville.in.the.next.two.years.',
          'What.neighborhood.do.you.live.in.', 'Are.you.a.student.', 'Ward',
          'How.satisfied.are.you.with.your.neighborhood.',
          'Precinct']

city_2015_raw = city_2015_nonull.drop(rem2015, axis=1)

city_2015_raw.shape

(185, 12)

### Modifying the column names for better data consistency

In [17]:
renamed_cols = ['Combined_ID','year','happiness_index','satisfaction_life_index','satisfaction_place_index','quality_public_schools',
'local_police_effectiveness','sex','age','race','time_lived','annual_household_income']

In [20]:
city_2011_raw.columns = renamed_cols

city_2015_raw.columns = renamed_cols

city_2013_raw.columns = renamed_cols

### Merged the three datasets 

In [21]:
data = [city_2011_raw,city_2013_raw,city_2015_raw]

city_final = pd.concat(data)

city_final.shape

(6545, 12)

#### Dropping the combinedID columns as Column ID is not significant for the model

In [22]:
city_final1 = city_final.drop('Combined_ID',axis=1)


### Dropping the rows having Null target value 

city_final1 = city_final1[city_final1.happiness_index.notnull()]

In [23]:
renamed_cols1 = ['year','happiness_index','satisfaction_life_index','satisfaction_place_index','quality_public_schools',
'local_police_effectiveness','sex','age','race','time_lived','annual_household_income']
city_final1.shape

(6544, 11)

### Removing non-numeric values from the entire dataset

In [24]:
df = city_final1.applymap(lambda x: 'NA' if (x == '9*' or x == 'R' or x == 'i' or x == 'X' or x == 'r' or x == 'F' or x == 'n'
                                             or x == 'e' or x == '3f' or x == '5/27/2011' or x == '5/19/2011'
                                            or x == '6/6/2011' or x == '6/1/2011') else x)

len(df)

df1 = df.dropna(axis=0,how='any')

len(df1)

6388

### Extracting the Target Variable

In [34]:
city_final_target = df1['happiness_index']

city_final_var = df1.drop('happiness_index',axis=1)

### Creating the dummy variables for the categorical variables

In [54]:
city_final_var = pd.get_dummies(city_final_var)
city_final_var.shape

(6388, 154)

### Splitting the dataset into Train and Test sets: 70 - 30

In [36]:
X_train, X_test, y_train, y_test = train_test_split(city_final_var, city_final_target , test_size=0.3, random_state=0)

happiness_model1 = LogisticRegression(random_state=0)

happiness_model = happiness_model1.fit(X_train,y_train)

### Building Confusion Matrix

In [37]:
Y_HAT = happiness_model.predict(X_test)

conf_matrix = confusion_matrix(y_test,Y_HAT)

print(conf_matrix)

[[ 18   4   2   1   1   0   0   2   0   0   1   0   0   0   0   0]
 [  0 199   0   0   0   1   0   1   3   0  25   0   0  21   0   1]
 [  2   0   5   3   3   2   0   1   1   0   3   0   0   1   0   0]
 [  0   0   5  17   5   9   0   8   4   0   5   0   0   2   0   0]
 [  2   0   2   5  27  13   0  10   6   0   4   0   0   0   0   0]
 [  0   1   0   4  16  63   0  13  14   0   7   0   0   4   0   0]
 [  0   0   0   1   0   1   0   0   1   0   0   0   0   1   0   0]
 [  0   3   0   1  11   9   0  56  34   0  24   0   0   3   0   3]
 [  0   5   0   0   5  13   0  43 167   0  93   0   0  25   0   0]
 [  0   0   0   0   0   0   0   0   0   4   2   0   0   0   0   0]
 [  0  21   0   2   1   4   0  13  78   0 304   0   0 109   0   2]
 [  0   0   0   0   0   0   0   0   0   1   0   2   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0]
 [  1  27   0   0   0   1   0   3  10   0  49   0   0 191   0   0]
 [  0   0   0   0   0   0   0   0   1   0   2   0   0   1   0 

### Calculating the Accuracy of the model

In [64]:
acc = happiness_model.score(X_test,y_test)
print('Accuracy of logistic regression classifier on test set {:.2f} '.format(happiness_model.score(X_test,y_test)))

Accuracy of logistic regression classifier on test set 0.57 


0.56598852373500264

### Calculating Recall and Precision

In [42]:
print (metrics.classification_report(y_test, Y_HAT))

             precision    recall  f1-score   support

          1       0.78      0.62      0.69        29
         10       0.76      0.79      0.78       251
          2       0.36      0.24      0.29        21
          3       0.49      0.31      0.38        55
          4       0.39      0.39      0.39        69
          5       0.54      0.52      0.53       122
        5.5       0.00      0.00      0.00         4
          6       0.37      0.39      0.38       144
          7       0.52      0.48      0.50       351
        7.5       0.80      0.67      0.73         6
          8       0.58      0.57      0.58       534
        8.5       1.00      0.50      0.67         4
         88       0.00      0.00      0.00         1
          9       0.53      0.68      0.60       282
        9.5       0.00      0.00      0.00         4
         NA       0.84      0.80      0.82        40

avg / total       0.56      0.57      0.56      1917



/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [66]:
#this is assertion block which verifies the solution.

try:
    def verify_answer(x):

         
        if x > .50: 
            return True
        else:
            return False
        

    ref_assert_var = verify_answer(acc)
except Exception as e:
    print('Your assertion block throws error: ' + str(e))
else:
    if ref_assert_var:
        print('Well done team')
    else:
        print('The answer did not pass the test.')

Well done team
